//
//  RPGStatusCodes.m
//  RPG Game
//
//  Created by Костянтин Паляничко on 10/19/16.
//  Copyright © 2016 RPG-team. All rights reserved.
//

#define RPGSTATUSCODES_OK_WORD_TOKEN @"OK"

#import "RPGStatusCodes.h"

NSString * const RPGStatusCodeDescription[] =
{
    // Server Status Codes
  [kRPGStatusCodeOK] = @"OK",
  [kRPGStatusCodeWrongJSON] = @"Wrong JSON",
  [kRPGStatusCodeUserDoesNotExist] = @"User does not exist",
  [kRPGStatusCodeWrongEmail] = @"Wrong email",
  [kRPGStatusCodeWrongPassword] = @"Wrong password",
  [kRPGStatusCodeWrongToken] = @"Wrong token",
  [kRPGStatusCodeUsernameAlreadyTaken] = @"Username is already taken",
  [kRPGStatusCodeEmailAlreadyTaken] = @"Email is already taken",
  [kRPGStatusCodeQuestWithSuchIDNotFound] = @"Quest with such ID not found",
  [kRPGStatusCodeUserHasNoSuchCharacter] = @"User has no such character",
  [kRPGStatusCodeSkillWithSuchIDNotFound] = @"Skill with such ID not found",
  [kRPGStatusCodeNotYourTurn] = @"Not your turn",
  [kRPGStatusCodeSkillOnCooldownOrDoesNotExist] = @"Skill is on cooldown or does not exist",
  [kRPGStatusCodeRunOutOfTime] = @"Run out of time",
  [kRPGStatusCodeQuestAlreadyInProgress] = @"Quest is already in progress",
  [kRPGStatusCodeServerDidNotGetFile] = @"Server did not get file",
  [kRPGStatusCodeUserHasNoSuchQuest] = @"User has no such quest",
  [kRPGStatusCodeNotPicture] = @"Not a picture",
  [kRPGStatusCodeTooBigPicture] = @"Too big picture",
  [kRPGStatusCodeTurnAction] = @"Turn action",
  [kRPGStatusCodeWrongClass] = @"Wrong class",
  [kRPGStatusCodeClassNotFound] = @"Class not found",
  [kRPGStatusCodeBattleDoesNotExist] = @"Battle does not exist",
  [kRPGStatusCodeQuestNotAccepted] = @"Quest is not accepted",
  [kRPGStatusCodeQuestNotSkipped] = @"Quest is not skipped",
  [kRPGStatusCodeNoQuestForVoting] = @"No quest for voting",
  [kRPGStatusCodeClassesNotFound] = @"ClassesNotFound",
  [kRPGStatusCodeDefaultError] = @"Something went wrong",
  [kRPGStatusCodeEmptySkillsToSelect] = @"Empty skills",
  [kRPGStatusCodeHasNoSuchSkills] = @"Has no such skills",
  [kRPGStatusCodeHasNoAnySkills] = @"Has no such skills",
  [kRPGStatusCodeExceedActiveSkillsBagSize] = @"Exceed bag size",
  [kRPGStatusCodeCharacterLevelIsLesserThanSkills] = @"Character level isn't enough",
  [kRPGStatusCodeNotEnoughMoney] = @"Not enough money",
  [kRPGStatusCodeWrongUnit] = @"Wrong unit",
  [kRPGStatusCodeUnitIsAlreadyBought] = @"Unit is already bought",
  [kRPGStatusCodeInsufficientCrystalsAmount] = @"Insufficient crystal amount",
  [kRPGStatusCodeDifferentClassOfCharacterAndQuest] = @"Inappropriate class for this quest",
  [kRPGStatusCodeLevelOfCharacterAndQuest] = @"Inappropriate character level for this quest",
  [kRPGStatusCodeTooShortUsername] = @"Too short username",
  [kRPGStatusCodeTooLongUsername] = @"Too long username",
  [kRPGStatusCodeTooShortPassword] = @"Too short password",
  [kRPGStatusCodeTooLongPassword] = @"Too long password",
  [kRPGStatusCodeTooShortCharacterName] = @"Too short character name",
  [kRPGStatusCodeTooLongCharacterName] = @"Too long character name",
  [kRPGStatusCodeInvalidUsername] = @"Invalid username",
  [kRPGStatusCodeInvalidCharacterName] = @"Invalid character name",
  [kRPGStatusCodeUndefinedSymbolsInUsername] = @"Undefined symbols in username",
  [kRPGStatusCodeUndefinedSymbolsInCharacterName] = @"Undefined symbols in character name",
  
    // RPGNetworkManager Status Codes
  [kRPGStatusCodeNetworkManagerUnknown] = @"Unknown network error",
  [kRPGStatusCodeNetworkManagerEmptyResponseData] = @"Response data is empty",
  [kRPGStatusCodeNetworkManagerServerError] = @"External server error",
  [kRPGStatusCodeNetworkManagerSerializingError] = @"Respose data serialization error",
  [kRPGStatusCodeNetworkManagerNoInternetConnection] = @"No Internet connection",
  [kRPGStatusCodeNetworkManagerResponseObjectValidationFail] = @"Response object validation failure"
};

NSString * const RPGStatusCodeTitle[] =
{
    // Server Status Codes
  [kRPGStatusCodeWrongJSON] = @"JSON Error",
  [kRPGStatusCodeUserDoesNotExist] = @"Error",
  [kRPGStatusCodeWrongEmail] = @"Error",
  [kRPGStatusCodeWrongPassword] = @"Error",
  [kRPGStatusCodeWrongToken] = @"Error",
  [kRPGStatusCodeUsernameAlreadyTaken] = @"Registration error",
  [kRPGStatusCodeEmailAlreadyTaken] = @"Registration error",
  [kRPGStatusCodeQuestWithSuchIDNotFound] = @"Quest error",
  [kRPGStatusCodeUserHasNoSuchCharacter] = @"Invalid character request",
  [kRPGStatusCodeSkillWithSuchIDNotFound] = @"Skills error",
  [kRPGStatusCodeNotYourTurn] = @"Battle error",
  [kRPGStatusCodeSkillOnCooldownOrDoesNotExist] = @"Skill error",
  [kRPGStatusCodeRunOutOfTime] = @"Battle error",
  [kRPGStatusCodeQuestAlreadyInProgress] = @"Quest error",
  [kRPGStatusCodeServerDidNotGetFile] = @"Server error",
  [kRPGStatusCodeUserHasNoSuchQuest] = @"Quest error",
  [kRPGStatusCodeNotPicture] = @"Server error",
  [kRPGStatusCodeTooBigPicture] = @"Server error",
  [kRPGStatusCodeTurnAction] = @"Error",
  [kRPGStatusCodeWrongClass] = @"Registration error",
  [kRPGStatusCodeClassNotFound] = @"Registration error",
  [kRPGStatusCodeBattleDoesNotExist] = @"Battle error",
  [kRPGStatusCodeQuestNotAccepted] = @"Quest error",
  [kRPGStatusCodeQuestNotSkipped] = @"Quest error",
  [kRPGStatusCodeNoQuestForVoting] = @"Quest error",
  [kRPGStatusCodeClassesNotFound] = @"Class error",
  [kRPGStatusCodeDefaultError] = @"Error",
  [kRPGStatusCodeEmptySkillsToSelect] = @"Character profile error",
  [kRPGStatusCodeHasNoSuchSkills] = @"Character profile error",
  [kRPGStatusCodeHasNoAnySkills] = @"Character profile error",
  [kRPGStatusCodeExceedActiveSkillsBagSize] = @"Character profile error",
  [kRPGStatusCodeCharacterLevelIsLesserThanSkills] = @"Character profile error",
  [kRPGStatusCodeNotEnoughMoney] = @"Shop error",
  [kRPGStatusCodeWrongUnit] = @"Shop error",
  [kRPGStatusCodeUnitIsAlreadyBought] = @"Shop error",
  [kRPGStatusCodeInsufficientCrystalsAmount] = @"Shop error",
  [kRPGStatusCodeDifferentClassOfCharacterAndQuest] = @"Quest error",
  [kRPGStatusCodeLevelOfCharacterAndQuest] = @"Quest error",
  [kRPGStatusCodeTooShortUsername] = @"Registration error",
  [kRPGStatusCodeTooLongUsername] = @"Registration error",
  [kRPGStatusCodeTooShortPassword] = @"Registration error",
  [kRPGStatusCodeTooLongPassword] = @"Registration error",
  [kRPGStatusCodeTooShortCharacterName] = @"Registration error",
  [kRPGStatusCodeTooLongCharacterName] = @"Registration error",
  [kRPGStatusCodeInvalidUsername] = @"Registration error",
  [kRPGStatusCodeInvalidCharacterName] = @"Registration error",
  [kRPGStatusCodeUndefinedSymbolsInUsername] = @"Registration error",
  [kRPGStatusCodeUndefinedSymbolsInCharacterName] = @"Registration error",
  
    // RPGNetworkManager Status Codes
  [kRPGStatusCodeNetworkManagerUnknown] = @"Network error",
  [kRPGStatusCodeNetworkManagerEmptyResponseData] = @"Network error",
  [kRPGStatusCodeNetworkManagerServerError] = @"Network error",
  [kRPGStatusCodeNetworkManagerSerializingError] = @"Network error",
  [kRPGStatusCodeNetworkManagerNoInternetConnection] = @"Network error",
  [kRPGStatusCodeNetworkManagerResponseObjectValidationFail] = @"Network error"
};



NSString * const RPGStatusCodeActionTitle[] =
{
    // Server Status Codes
  [kRPGStatusCodeWrongJSON] = @"Go to login screen",
  [kRPGStatusCodeUserDoesNotExist] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeWrongEmail] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeWrongPassword] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeWrongToken] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUsernameAlreadyTaken] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeEmailAlreadyTaken] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeQuestWithSuchIDNotFound] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUserHasNoSuchCharacter] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeSkillWithSuchIDNotFound] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNotYourTurn] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeSkillOnCooldownOrDoesNotExist] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeRunOutOfTime] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeQuestAlreadyInProgress] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeServerDidNotGetFile] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUserHasNoSuchQuest] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNotPicture] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooBigPicture] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTurnAction] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeWrongClass] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeClassNotFound] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeBattleDoesNotExist] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeQuestNotAccepted] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeQuestNotSkipped] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNoQuestForVoting] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeClassesNotFound] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeDefaultError] = RPGSTATUSCODES_OK_WORD_TOKEN,
  
  [kRPGStatusCodeEmptySkillsToSelect] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeHasNoSuchSkills] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeHasNoAnySkills] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeExceedActiveSkillsBagSize] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeCharacterLevelIsLesserThanSkills] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNotEnoughMoney] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeWrongUnit] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUnitIsAlreadyBought] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeInsufficientCrystalsAmount] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeDifferentClassOfCharacterAndQuest] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeLevelOfCharacterAndQuest] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooShortUsername] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooLongUsername] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooShortPassword] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooLongPassword] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooShortCharacterName] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeTooLongCharacterName] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeInvalidUsername] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeInvalidCharacterName] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUndefinedSymbolsInUsername] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeUndefinedSymbolsInCharacterName] = RPGSTATUSCODES_OK_WORD_TOKEN,
  
    // RPGNetworkManager Status Codes
  [kRPGStatusCodeNetworkManagerUnknown] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNetworkManagerEmptyResponseData] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNetworkManagerServerError] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNetworkManagerSerializingError] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNetworkManagerNoInternetConnection] = RPGSTATUSCODES_OK_WORD_TOKEN,
  [kRPGStatusCodeNetworkManagerResponseObjectValidationFail] = RPGSTATUSCODES_OK_WORD_TOKEN
};
